-- Correct Values generated by PHP
INSERT INTO usuario (nome, email, login, senha, tipo, ativo) VALUES 
('Gestor Admin', 'admin@sistema.com', 'admin', '$2y$10$Vp3QzysidOBSOrgIEYqzTe4uKxM9zYnaQSHJ1EzMhC9/XdPZPU6y2', 'gestor', '1');

INSERT INTO usuario (nome, email, login, senha, tipo, ativo) VALUES 
('Cliente Teste', 'cliente@sistema.com', 'user', '$2y$10$MSFdgncOkY7/oS3TG6fjpumA4w5u7HUQX3Z7cjoKNOXa/CxkeABqq', 'cliente', '1');
