<?php
// Fix both logins and export
require_once 'init.php';

try {
    TTransaction::open('database');
    
    // 1. Fix Admin
    $admin = Usuario::where('login', '=', 'admin')->first();
    if (!$admin) {
        $admin = new Usuario;
        $admin->login = 'admin';
        $admin->nome = 'Gestor Admin';
        $admin->email = 'admin@sistema.com';
        $admin->tipo = 'gestor';
        $admin->ativo = '1';
    }
    $hash_admin = password_hash('admin', PASSWORD_DEFAULT);
    $admin->senha = $hash_admin;
    $admin->store();
    
    // 2. Fix User
    $user = Usuario::where('login', '=', 'user')->first();
    if (!$user) {
        $user = new Usuario;
        $user->login = 'user';
        $user->nome = 'Cliente Teste';
        $user->email = 'cliente@sistema.com';
        $user->tipo = 'cliente';
        $user->ativo = '1';
    }
    $hash_user = password_hash('user', PASSWORD_DEFAULT);
    $user->senha = $hash_user;
    $user->store();
    
    TTransaction::close();
    
    // Write SQL snippet to file
    $sql = "-- Correct Values generated by PHP\n";
    $sql .= "INSERT INTO usuario (nome, email, login, senha, tipo, ativo) VALUES \n";
    $sql .= "('Gestor Admin', 'admin@sistema.com', 'admin', '{$hash_admin}', 'gestor', '1');\n\n";
    $sql .= "INSERT INTO usuario (nome, email, login, senha, tipo, ativo) VALUES \n";
    $sql .= "('Cliente Teste', 'cliente@sistema.com', 'user', '{$hash_user}', 'cliente', '1');\n";
    
    file_put_contents('credentials.sql', $sql);
    echo "Fixed DB and exported credentials.sql";
    
} catch (Exception $e) {
    echo $e->getMessage();
}
